# Generated by Django 5.0.7 on 2024-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='..........................................', max_length=42)),
                ('current_player', models.IntegerField(default=1)),
            ],
        ),
    ]
